import uuid from 'uuid/v1';
import guest1 from "assets/img/faces/avatar.jpg";
import guest2 from "assets/img/faces/christian.jpg";
import guest3 from "assets/img/faces/kendall.jpg";
import client1 from "assets/client-1.jpg";
import client2 from "assets/client-2.png";
import client3 from "assets/client-3.png";
import volunteer1 from "assets/img/faces/avatar.jpg";
import volunteer2 from "assets/img/faces/christian.jpg";
import volunteer3 from "assets/img/faces/kendall.jpg";
export default [
  {
    __id: uuid(),
    external_name: 'Guest 1',
    external_type: 'Guest',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: guest1,
  },
  {
    _id: uuid(),
    external_name: 'Guest 2',
    external_type: 'Guest',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: guest2,
  },
  {
    _id: uuid(),
    external_name: 'Guest 3',
    external_type: 'Guest',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: guest3,
  },
  {
    _id: uuid(),
    external_name: 'Client 1',
    external_type: 'Sponsor',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: client1,
  },
  {
    _id: uuid(),
    external_name: 'Client 2',
    external_type: 'Sponsor',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: client2,
  },
  {
    _id: uuid(),
    external_name: 'Client 3',
    external_type: 'Sponsor',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: client3,
  },
  {
    _id: uuid(),
    external_name: 'Volunteer 1',
    external_type: 'Volunteer',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: volunteer1,
  },
  {
    _id: uuid(),
    external_name: 'Volunteer 2',
    external_type: 'Volunteer',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: volunteer2,
  },
  {
    _id: uuid(),
    external_name: 'Volunteer 3',
    external_type: 'Volunteer',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: volunteer3,
  },
  {
    _id: uuid(),
    external_name: 'Media Partner 1',
    external_type: 'Media Partner',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: client1,
  },
  {
    _id: uuid(),
    external_name: 'Media Partner 2',
    external_type: 'Media Partner',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: client2,
  },
  {
    _id: uuid(),
    external_name: 'Media Partner 3',
    external_type: 'Media Partner',
    email: 'a@gmail.com',
    event_id: '0',
    phone_number: '081615627998',
    details: 'Details goes in this section',
    picture: client3,
  },
];
